name: melodium-ci

on:
  push:

jobs:
  melodium:
    uses: melodium-tech/github-actions/.github/workflows/melodium-local-distrib.yml@v0.10.0
    with:
      melodium_images_pull_source: registry.gitlab.com/melodium/containers
      command: |
        run --api-report Compo.toml advanced --repository_clone_url '${{ github.repositoryUrl }}' --repository_clone_ref '${{ github.ref_name }}'
      artifact-path: 'output/'
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
